all:
  children:
    app_servers:
      hosts:
        app-server-1:
          ansible_host: "{{ app_server_ip }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/retailmax-key.pem
          app_name: retailmax
          app_port: 8080
          ecr_repository_url: "{{ ecr_repo_url }}"
          aws_region: us-east-1
      vars:
        ansible_python_interpreter: /usr/bin/python3

    monitoring_servers:
      hosts:
        monitoring-server-1:
          ansible_host: "{{ monitoring_server_ip }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/retailmax-key.pem
          prometheus_port: 9090
          grafana_port: 3000
          node_exporter_port: 9100
      vars:
        ansible_python_interpreter: /usr/bin/python3

    jenkins_servers:
      hosts:
        jenkins-server-1:
          ansible_host: "{{ jenkins_server_ip }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/retailmax-key.pem
          jenkins_port: 8080
      vars:
        ansible_python_interpreter: /usr/bin/python3

  vars:
    # Global variables
    project_name: retailmax
    aws_region: us-east-1
    
    # Application variables
    app_server_ip: "{{ lookup('env', 'APP_SERVER_IP') | default('your-app-server-ip') }}"
    ecr_repo_url: "{{ lookup('env', 'ECR_REPO_URL') | default('your-ecr-repo-url') }}"
    
    # Monitoring variables
    monitoring_server_ip: "{{ lookup('env', 'MONITORING_SERVER_IP') | default('your-monitoring-server-ip') }}"
    
    # Jenkins variables
    jenkins_server_ip: "{{ lookup('env', 'JENKINS_SERVER_IP') | default('your-jenkins-server-ip') }}" 