all:
  children:
    app_servers:
      hosts:
        app-server:
          ansible_host: "{{ lookup('env', 'APP_SERVER_IP', default='localhost') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          app_name: retailmax
          app_port: 8080
          ecr_repository_url: "{{ lookup('env', 'ECR_REPOSITORY_URL') }}"
          aws_region: "{{ lookup('env', 'AWS_REGION') }}"
    
    monitoring_servers:
      hosts:
        monitoring-server:
          ansible_host: "{{ lookup('env', 'MONITORING_SERVER_IP', default='localhost') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          prometheus_port: 9090
          grafana_port: 3000
    
    jenkins_servers:
      hosts:
        jenkins-server:
          ansible_host: "{{ lookup('env', 'JENKINS_SERVER_IP', default='localhost') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          jenkins_port: 8080
          jenkins_admin_password: "{{ lookup('env', 'JENKINS_ADMIN_PASSWORD', default='admin') }}"
    
  vars:
    ansible_python_interpreter: /usr/bin/python3
    aws_region: "{{ lookup('env', 'AWS_REGION') }}"
    project_name: "{{ lookup('env', 'PROJECT_NAME') }}"
    ecr_repository_url: "{{ lookup('env', 'ECR_REPOSITORY_URL') }}" 