FROM jenkins/jenkins:lts

USER root

# Install Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get update && apt-get install -y nodejs

# Install Docker CLI
RUN apt-get install -y docker.io

# Allow Jenkins user to access Docker
RUN usermod -aG docker jenkins

USER jenkins
